#! /bin/sh
### BEGIN INIT INFO
# Provides:          calleng-main
# Required-Start:    $syslog $all
# Required-Stop:     $syslog $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Callengine main
# Description:       Daemon to control main component of callengine
### END INIT INFO

# Author: David Ryder


# HOME is the location of your adhearsion project
HOME=/var/www/vhosts/callengine.logmycalls.com
NAME=callengine
DESC="Callengine main"
USER=root
GROUP=$USER

RUBY_PATH=/usr/local/rvm/bin/rvm-shell
GEMSET=1.9.2@callengine


# This is the path to your gemset - I'd like a better way to retrieve this value
export GEM_HOME=/usr/local/rvm/gems/ruby-1.9.2-p290@callengine

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:$GEM_HOME/bin
PIDFILE=$HOME/adhearsion.pid
SCRIPTNAME=/etc/init.d/$NAME

#
#	Function that starts the daemon/service.
#
d_start() {
	if ! start-stop-daemon --start --pidfile $PIDFILE \
                        --startas $RUBY_PATH --user $USER \
                        -- "$GEMSET" -c 'ahnctl start $HOME'; then
		echo " failed."
		exit 1
	fi

}

#
#	Function that stops the daemon/service.
#
d_stop() {
	if start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 3 == 0; then
		rm -f $PIDFILE
	else
		rm -f $PIDFILE
		echo " not running."
		exit 1
	fi
}

case "$1" in
  start)
	if [ -f $PIDFILE ]; then
		echo " failed (already running)."
		exit 1
	else
		d_start
		echo " ... done."
	fi
	;;
  stop)
	echo -n "Stopping $NAME..."
	if [ -f $PIDFILE ]; then
		d_stop
		echo " ... done."
	else
		if [ -f $PIDFILE]; then
		  rm $PIDFILE
		fi
		echo " ... not running."
		
	fi
	;;
  restart|force-reload)
	if [ -f $PIDFILE ]; then
		$0 stop
	fi
	$0 start
	exit 0
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

