#! /bin/sh
### BEGIN INIT INFO
# Provides:          calleng-main
# Required-Start:    $syslog $all
# Required-Stop:     $syslog $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Callengine main
# Description:       Daemon to control main component of callengine
### END INIT INFO

# Author: David Ryder

#set -e
HOME=/home/dryder/source/callengine/trunk
NAME=calleng-main
DESC="Callengine main"
USER=dryder
GROUP=$USER

# This is the path to your gemset - I'd like a better way to retrieve this value
export GEM_HOME=/home/dryder/.rvm/gems/ruby-1.8.7-p352@callengine

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:$GEM_HOME/bin
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Read configuration variable file if it is present - for future use
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
#	Function that starts the daemon/service.
#
d_start() {
	if ! start-stop-daemon --start --background --pidfile $PIDFILE \
			--chdir $HOME --make-pidfile --user $USER \
			--exec $GEM_HOME/bin/ahn -- start $HOME; then
		echo " failed."
		exit 1
	fi
}

#
#	Function that stops the daemon/service.
#
d_stop() {
	if start-stop-daemon --stop --quiet --pidfile $PIDFILE --name ahn --retry 3 == 0; then
		rm -f $PIDFILE
	else
		echo " failed."
		exit 1
	fi
}

case "$1" in
  start)
	echo -n "Starting $NAME..."
	if [ -f $PIDFILE ]; then
		echo " failed (already running)."
		exit 1
	else
		d_start
		echo " done."
	fi
	;;
  stop)
	echo -n "Stopping $NAME..."
	if [ -f $PIDFILE ]; then
		d_stop
		echo " done."
	else
		echo " failed (not running)."
		exit 1
	fi
	;;
  restart|force-reload)
	if [ -f $PIDFILE ]; then
		$0 stop
	fi
	$0 start
	exit 0
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

